# Change these first
owner: sabilyfd # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: LMS
    url: https://training.shibirsec.qzz.io
  - name: Office
    url: https://shughran.com


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: status.teamsabily.qzz.io
  baseUrl: /status
  theme: night
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Sabily Status
  introTitle: "Status Page for Team Sabily"
  introMessage: Status page for Team Sabily
  navbar:
    - title: Status
      href: /

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 5 * * *"
  uptime: "*/50 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
